name: Documentation

on: [push]

jobs:
  build:
    name: Build and publish documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install depedencies
        run: |
          sudo apt update

          # GEOS
          sudo apt install -y libgeos-dev

          # Doxygen v1.8.18
          #   Note: We do not get doxygen from apt, we instead install the precompiled binaries
          #     This is becasue extenal image URLs are not supported properly in older versions
          wget https://excellmedia.dl.sourceforge.net/project/doxygen/rel-1.8.18/doxygen-1.8.18.linux.bin.tar.gz
          tar xf doxygen-1.8.18.linux.bin.tar.gz
          cd doxygen-1.8.18
          sudo make install

          # m.css depedencies
          pip3 install jinja2 Pygments

      - name: Build C++ docs
        run: |
          cmake -B build/docs -S documentation
          cmake --build build/docs --target cppdocs

      - name: Publish on Github Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/docs/cppdocs/html
