name: Documentation

on: [push]

jobs:
  build:
    name: Build and publish documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install depedencies
        run: |
          sudo apt update

          # GEOS, Doxygen
          sudo apt install -y doxygen libgeos-dev

          # m.css depedencies
          pip3 install jinja2 Pygments

      - name: Build C++ docs
        run: |
          cmake -B build/docs -S documentation
          cmake --build build/docs --target cppdocs

      - name: Publish on Github Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/docs/cppdocs/html
